baseURL = "https://www.lavalampsystem.com/"
languageCode = "en-US"
title = "The Lavalamp System"

[params]
description = "Reflections and essays on plurality"
author = "Lavalamp System"

[taxonomies]
category = "categories"
tag = "tags"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
